# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

# generate fibonacci sequence

fib = [0,1]
while True:
    f = fib[-2]+fib[-1]
    if f > 4000000:
        break
    fib.append(f)
# print(fib)
t = 0
for num in fib:
    if num % 2 == 0:
        t += num

print(t)